package view.usuario;

import core.Sistema;
import javax.swing.JOptionPane;
import models.Categoria;

/**
 *
 * @author Grupo
 * @version 1.0
 * 
 */
public class EditarPerfil extends javax.swing.JDialog {

    Categoria categoria;

    /**
     * Creates new form AdicionarCategoria
     */
    public EditarPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(editarButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        labelDica = new javax.swing.JLabel();
        inputDica = new javax.swing.JTextField();
        labelNovaSenha = new javax.swing.JLabel();
        labelConfirmaSenha = new javax.swing.JLabel();
        inputNovaSenha = new javax.swing.JPasswordField();
        inputConfirmaSenha = new javax.swing.JPasswordField();
        avisoLabel = new javax.swing.JLabel();
        mudarEmailButton = new javax.swing.JButton();
        inputEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dark Side of the Grana - Editar Perfil");

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Editar perfil");

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setText("Nome :");

        inputNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNome.setText(Sistema.instance.getUsuarioLogado().getNome());

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setText("E-mail:");

        editarButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/pencil.png"))); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/arrow_left.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelDica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDica.setText("Dica de senha:");

        inputDica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputDica.setText(Sistema.instance.getUsuarioLogado().getDicaDeSenha());

        labelNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNovaSenha.setText("Nova Senha:");

        labelConfirmaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConfirmaSenha.setText("Confirma senha:");

        inputNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        inputConfirmaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        avisoLabel.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        avisoLabel.setText("Caso não queira mudar a senha, deixe em branco");

        mudarEmailButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        mudarEmailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/email_edit.png"))); // NOI18N
        mudarEmailButton.setText("Trocar e-mail");
        mudarEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarEmailButtonActionPerformed(evt);
            }
        });

        inputEmail.setEditable(false);
        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmail.setText(Sistema.instance.getUsuarioLogado().getEmail());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelNovaSenha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDica)
                            .addComponent(labelConfirmaSenha)
                            .addComponent(labelNome)
                            .addComponent(labelEmail))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputConfirmaSenha)
                            .addComponent(inputNovaSenha)
                            .addComponent(inputDica)
                            .addComponent(inputNome)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(avisoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputEmail)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar)
                        .addGap(17, 17, 17)
                        .addComponent(mudarEmailButton)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(191, 191, 191))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelTitulo)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDica)
                    .addComponent(inputDica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovaSenha)
                    .addComponent(inputNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelConfirmaSenha)
                    .addComponent(inputConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avisoLabel)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mudarEmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        try{
            if (getSenha().isEmpty() && getConfirmaSenha().isEmpty()) {
                Sistema.instance.editaUsuario(getNome(), null, getDica());
            } else {
                comparaSenha(getSenha(), getConfirmaSenha());
                Sistema.instance.editaUsuario(getNome(), getSenha(), getDica());
            }
            JOptionPane.showMessageDialog(rootPane, "Perfil editado com sucesso.");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void mudarEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarEmailButtonActionPerformed
        EditarEmail editarEmail = new EditarEmail(null, rootPaneCheckingEnabled);
        editarEmail.setVisible(true);
        dispose();
    }//GEN-LAST:event_mudarEmailButtonActionPerformed

    private String getNome() {
        return inputNome.getText();
    }
    
    private String getSenha() {
        return String.valueOf(inputNovaSenha.getPassword());
    }

    private String getConfirmaSenha() {
        return String.valueOf(inputConfirmaSenha.getPassword());
    }

    private void comparaSenha(String senha, String confirmaSenha)
            throws Exception {
        if (!senha.equals(confirmaSenha)) {
            throw new Exception("Senhas não conferem.");
        }
    }
    
    private String getDica() {
        return inputDica.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton editarButton;
    private javax.swing.JPasswordField inputConfirmaSenha;
    private javax.swing.JTextField inputDica;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputNovaSenha;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelConfirmaSenha;
    private javax.swing.JLabel labelDica;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNovaSenha;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JButton mudarEmailButton;
    // End of variables declaration//GEN-END:variables
}
