/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import core.Sistema;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class EditarEmail extends javax.swing.JDialog {

    /**
     * Creates new form EditarEmail
     */
    public EditarEmail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(botaoEditarEmail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoEditarEmail = new javax.swing.JButton();
        labelNovoEmail = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        inputConfirmaEmail = new javax.swing.JTextField();
        inputNovoEmail = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        labelConfirma = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dark Side of the Grana - Editar E-mail");

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        botaoEditarEmail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoEditarEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/pencil.png"))); // NOI18N
        botaoEditarEmail.setText("Editar");
        botaoEditarEmail.setToolTipText("");
        botaoEditarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarEmailActionPerformed(evt);
            }
        });

        labelNovoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNovoEmail.setText("Novo e-mail:");

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/arrow_left.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelConfirma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConfirma.setText("Confirme:");

        labelSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSenha.setText("Digite sua senha:");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Editar E-mail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(labelTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNovoEmail)
                                    .addComponent(labelConfirma))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputNovoEmail)
                                    .addComponent(inputConfirmaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelSenha)
                        .addGap(36, 36, 36)
                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoEditarEmail)
                .addGap(17, 17, 17)
                .addComponent(botaoVoltar)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovoEmail)
                    .addComponent(inputNovoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirma)
                    .addComponent(inputConfirmaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoEditarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarEmailActionPerformed
        try {
            comparaEmail(getNovoEmail(), getConfirmaEmail());
            testaSenha(getSenha());
            Sistema.instance.editaEmailDoUsuario(getNovoEmail());
            JOptionPane.showMessageDialog(rootPane, "E-mail editado com sucesso.");
            dispose();
            EditarPerfil editarPerfil = new EditarPerfil(null, rootPaneCheckingEnabled);
            editarPerfil.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_botaoEditarEmailActionPerformed

    private String getNovoEmail() {
        return inputNovoEmail.getText();
    }

    private String getConfirmaEmail() {
        return inputConfirmaEmail.getText();
    }

    private String getSenha() {
        return String.valueOf(inputSenha.getPassword());
    }

    private void comparaEmail(String email, String confirmaEmail)
            throws Exception {
        if (!email.equals(confirmaEmail)) {
            throw new Exception("E-mails não conferem.");
        }
    }

    private static String criptografar(String pass) throws NoSuchAlgorithmException {
        MessageDigest m = MessageDigest.getInstance("MD5");
        byte[] data = pass.getBytes();
        m.update(data, 0, data.length);
        BigInteger i = new BigInteger(1, m.digest());
        return String.format("%1$032X", i);
    }

    private void testaSenha(String novaSenha) throws Exception {
        novaSenha = criptografar(novaSenha);
        if (!novaSenha.equals(Sistema.instance.getUsuarioLogado().getSenha())) {
            throw new Exception("Senha errada.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarEmail;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField inputConfirmaEmail;
    private javax.swing.JTextField inputNovoEmail;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelConfirma;
    private javax.swing.JLabel labelNovoEmail;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
