/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.transacao;

import models.Recorrencia;
import core.Sistema;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Categoria;

/**
 *
 * @author Grupo
 * @version 1.0
 */
public class AdicionarTransacao extends javax.swing.JDialog {

    /**
     * Creates new form AdicionarTransacao
     */
    public AdicionarTransacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(botaoEnviar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiposDeTransacao = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        labelDescricao = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelRecorrencia = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        inputDescricao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        radioProvento = new javax.swing.JRadioButton();
        selectCategoria = new javax.swing.JComboBox();
        selectRecorrencia = new javax.swing.JComboBox();
        botaoEnviar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        inputValor = new javax.swing.JTextField();
        inputData = new com.toedter.calendar.JDateChooser();
        labelConta = new javax.swing.JLabel();
        selecionarConta = new javax.swing.JComboBox();
        radioDespesa = new javax.swing.JRadioButton();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dark Side of the Grana - Adicionar Transação");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDescricao.setText("Descrição :");

        labelValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValor.setText("Valor :");

        labelCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCategoria.setText("Categoria :");

        labelData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelData.setText("Data :");

        labelRecorrencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRecorrencia.setText("Recorrencia:");

        labelTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipo.setText("Tipo :");

        inputDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(251, 251, 251));

        radioProvento.setBackground(new java.awt.Color(251, 251, 251));
        tiposDeTransacao.add(radioProvento);
        radioProvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioProvento.setText("Provento");
        radioProvento.setActionCommand("Provento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioProvento)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(radioProvento))
        );

        selectCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectCategoria.setModel(listaDeCategoria());
        selectCategoria.setPreferredSize(new java.awt.Dimension(300, 30));

        selectRecorrencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectRecorrencia.setModel(new DefaultComboBoxModel(Recorrencia.values()));
        selectRecorrencia.setSelectedIndex(0);
        selectRecorrencia.setPreferredSize(new java.awt.Dimension(300, 30));

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/accept.png"))); // NOI18N
        botaoEnviar.setText("Criar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/arrow_left.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        inputValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        inputData.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        labelConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConta.setText("Conta :");

        selecionarConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selecionarConta.setModel(listaDeConta());

        radioDespesa.setBackground(new java.awt.Color(251, 251, 251));
        tiposDeTransacao.add(radioDespesa);
        radioDespesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioDespesa.setSelected(true);
        radioDespesa.setText("Despesa");
        radioDespesa.setActionCommand("Despesa");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Criar Transação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescricao)
                            .addComponent(labelValor)
                            .addComponent(labelData)
                            .addComponent(labelTipo)
                            .addComponent(labelRecorrencia)
                            .addComponent(labelCategoria)
                            .addComponent(labelConta))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectCategoria, 0, 386, Short.MAX_VALUE)
                            .addComponent(inputDescricao)
                            .addComponent(selectRecorrencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputValor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selecionarConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioDespesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(botaoEnviar)
                        .addGap(20, 20, 20)
                        .addComponent(botaoVoltar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConta)
                    .addComponent(selecionarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao)
                    .addComponent(inputDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoria)
                    .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelData)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecorrencia)
                    .addComponent(selectRecorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTipo)
                        .addComponent(radioDespesa))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String getDescricao() {
        return inputDescricao.getText();
    }

    private double getValor() {
        return Double.parseDouble(inputValor.getText().replaceAll(",", "."));
    }

    private Calendar getData() {
        return inputData.getCalendar();
    }

    private String getTipo() {
        return tiposDeTransacao.getSelection().getActionCommand();
    }

    private int getRecorrencia() {
        Recorrencia nome = (Recorrencia) selectRecorrencia.getSelectedItem();
        return nome.getValor();
    }

    private String getCategoria() throws Exception {
        if (selectCategoria.getSelectedItem() == null) {
            throw new Exception("Não ha categoria selecionada.");
        }
        return (String) selectCategoria.getSelectedItem();
    }

    private String getConta() throws Exception {
        if (selecionarConta.getSelectedItem() == null) {
            throw new Exception("Não ha conta selecionada.");
        }
        return (String) selecionarConta.getSelectedItem();
    }


    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        try {
            Categoria categoria = Sistema.instance.pesquisaCategoria(getCategoria());
            Sistema.instance.adicionaTransacao(getDescricao(), getData(), categoria, getValor(), getRecorrencia(), getTipo(), getConta());
            if (categoria.getSaldo() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Transacao criada com sucesso.\nSeu saldo para essa categoria esta negativo (R$ " + categoria.getSaldo() + ").");
            } else if (categoria.getSaldo() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Transacao criada com sucesso.\nVoce atingiu o limite de orcamento da sua categoria.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Transacao criada com sucesso.");
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    public DefaultComboBoxModel listaDeConta() {
        ArrayList<String> strings = new ArrayList<>();
        for (int i = 0; i < Sistema.instance.getUsuarioLogado().getListaDeContas().size(); i++) {
            strings.add(Sistema.instance.getUsuarioLogado().getListaDeContas().get(i).getNome());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Iterator<String> it = strings.iterator(); it.hasNext();) {
            String string = it.next();
            model.addElement(string);
        }
        return model;
    }

    public DefaultComboBoxModel listaDeCategoria() {
        ArrayList<String> strings = new ArrayList<>();
        for (int i = 0; i < Sistema.instance.getCategorias().size(); i++) {
            strings.add(Sistema.instance.getCategorias().get(i).getNome());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Iterator<String> it = strings.iterator(); it.hasNext();) {
            String string = it.next();
            model.addElement(string);
        }
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoVoltar;
    private com.toedter.calendar.JDateChooser inputData;
    private javax.swing.JTextField inputDescricao;
    private javax.swing.JTextField inputValor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelRecorrencia;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JRadioButton radioDespesa;
    private javax.swing.JRadioButton radioProvento;
    private javax.swing.JComboBox selecionarConta;
    private javax.swing.JComboBox selectCategoria;
    private javax.swing.JComboBox selectRecorrencia;
    private javax.swing.ButtonGroup tiposDeTransacao;
    // End of variables declaration//GEN-END:variables
}
