package view.transacao;

import core.Sistema;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Conta;
import models.Transacao;

/**
 *
 * @author Grpo
 * @version 1.0
 */
public class RemoverTransacao extends javax.swing.JDialog {

    /**
     * Creates new form RemoverTransacao
     */
    public RemoverTransacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(botaoExcluir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelRemoverTransacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        botaoExcluir = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        selecionarConta = new javax.swing.JComboBox();
        labelConta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dark Side of the Grana - Remover Transação");

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        labelRemoverTransacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRemoverTransacao.setText("Remover Transação");

        tabela.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Data", "Valor", "Categoria", "Recorrência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        botaoExcluir.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/delete.png"))); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/arrow_left.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        selecionarConta.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        selecionarConta.setModel(listaDeConta(Sistema.instance.getUsuarioLogado().getListaDeContas()));
        selecionarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarContaActionPerformed(evt);
            }
        });

        labelConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConta.setText("Conta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(labelConta)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRemoverTransacao)
                                    .addComponent(selecionarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(botaoExcluir)
                                .addGap(113, 113, 113)
                                .addComponent(botaoVoltar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelRemoverTransacao)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConta))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo excluir essa Transação ?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            try {
                Sistema.instance.removeTransacao(getPosicaoTransacao(), getConta());

                ((DefaultTableModel) tabela.getModel()).removeRow(getPosicaoTransacao());

                JOptionPane.showMessageDialog(rootPane, "Transação removida com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma transação.");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void selecionarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarContaActionPerformed
        try {
            tabela.setModel(getTableModelTransacao(Sistema.instance.getListaDeTransacoes(getConta())));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        tabela.setDefaultRenderer(Object.class, new Renderizador());
    }//GEN-LAST:event_selecionarContaActionPerformed

    private int getPosicaoTransacao() throws Exception {
        if (tabela.getSelectedRow() < 0) {
            throw new Exception("Transação não selecionada.");
        }
        return tabela.getSelectedRow();
    }

    private String getConta() throws Exception {
        if (selecionarConta.getSelectedItem() == null) {
            throw new Exception("Não ha conta selecionada");
        }
        return (String) selecionarConta.getSelectedItem();
    }

    private DefaultTableModel getTableModelTransacao(List<Transacao> listaDeTransacoes) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(new String[]{"Descrição", "Data", "Valor", "Categoria", "Recorrência"});
        for (Iterator<Transacao> it = listaDeTransacoes.iterator(); it.hasNext();) {
            Transacao transacao = it.next();
            SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
            model.addRow(new String[]{transacao.getDescricao(),
                formataData.format(transacao.getDataDeInsercao().getTime()),
                String.valueOf(transacao.getValor()),
                transacao.getCategoria().getNome(),
                "" + transacao.getRecorrencia()});
        }

        return model;
    }

    private DefaultComboBoxModel listaDeConta(List<Conta> listaDeContas) {
        ArrayList<String> strings = new ArrayList<>();
        for (Iterator<Conta> it = listaDeContas.iterator(); it.hasNext();) {
            Conta cadaConta = it.next();
            strings.add(cadaConta.getNome());
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Iterator<String> it = strings.iterator(); it.hasNext();) {
            String string = it.next();
            model.addElement(string);
        }
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelRemoverTransacao;
    private javax.swing.JComboBox selecionarConta;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
