package view.categoria;

import core.Sistema;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo
 * @version 1.0
 */
public class AdicionarCategoria extends javax.swing.JDialog {

    /**
     * Creates new form AdicionarCategoria
     */
    public AdicionarCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(botaoAdicionar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        botaoAdicionar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoEscolherCor = new javax.swing.JButton();
        painelCorEscolhida = new javax.swing.JPanel();
        labelOrcamento = new javax.swing.JLabel();
        inputOrcamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dark Side of the Grana - Adicionar Categoria");

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Adicionar Categoria");

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setText("Nome :");

        inputNome.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        labelCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCor.setText("Cor :");

        botaoAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/accept.png"))); // NOI18N
        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/arrow_left.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoEscolherCor.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botaoEscolherCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/color_wheel.png"))); // NOI18N
        botaoEscolherCor.setText("Escolher Cor");
        botaoEscolherCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherCorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCorEscolhidaLayout = new javax.swing.GroupLayout(painelCorEscolhida);
        painelCorEscolhida.setLayout(painelCorEscolhidaLayout);
        painelCorEscolhidaLayout.setHorizontalGroup(
            painelCorEscolhidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        painelCorEscolhidaLayout.setVerticalGroup(
            painelCorEscolhidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        labelOrcamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelOrcamento.setText("Orçamento:");

        inputOrcamento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelOrcamento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputOrcamento))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelNome)
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTitulo)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputNome)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(botaoEscolherCor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(painelCorEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGap(50, 50, 50))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(labelCor)
                            .addGap(293, 293, 293)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botaoAdicionar)
                        .addGap(20, 20, 20)
                        .addComponent(botaoVoltar)
                        .addGap(81, 81, 81))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCor)
                    .addComponent(botaoEscolherCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCorEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrcamento)
                    .addComponent(inputOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        try {
            Sistema.instance.adicionaCategoria(getNome(),getCor(), getOrcamento());
            JOptionPane.showMessageDialog(rootPane, "Categoria criada com sucesso.");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoEscolherCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherCorActionPerformed
        painelCorEscolhida.setBackground(JColorChooser.showDialog(null, "Selecione uma Cor", Color.BLACK));
    }//GEN-LAST:event_botaoEscolherCorActionPerformed

    private String getNome(){
        return inputNome.getText();
    }
    
    private Color getCor() {
        return painelCorEscolhida.getBackground();
    }
    
    private double getOrcamento() {
        return Double.parseDouble(inputOrcamento.getText().replaceAll(",", "."));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoEscolherCor;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputOrcamento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelOrcamento;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelCorEscolhida;
    // End of variables declaration//GEN-END:variables
}
